name: Run tests and linter

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up --build --exit-code-from web
    - name: Run StandardRB
      run: docker-compose run --rm web bundle exec standardrb --format progress
