name: Run tests and linter

on:
  push:
    branches:
     - "*"
  pull_request:
    branches:
     - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        source docker.env
        docker-compose up --build --exit-code-from web
    - name: Run StandardRB
      run: docker-compose run --rm web bundle exec standardrb --format progress
